# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:           ' ' 
tagline:          '计算机硕士'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      <marquee scrollamount="10" ><a href="/niming-resume/" target="_blank">云南师范大学计算机应用技术 硕士研究生。 主要研究方向为计算机图形学、DirectX、OpenGL ES，目前使用平台有 Unity3D / Unreal Engine4，语言 C#、C++. </a></marquee>
url:              https://zhouniyao.github.io/
baseurl:          /

author:
  name:           'Ni Ming'
  url:            https://zhouniyao.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zhouniyao
